Repository sergej-stk/notekeeper, pull requests merged in 2024-11, with the labels that each got.

#4 Bugfix: Changed API Version to 3
  src/main/java/com/example/notekeeper/NoteController.java
Labels: bug

#7 Hotfix dependabot.yml
  .github/dependabot.yml
Labels: bug

#15 Code cleanup Note Controller
  src/main/java/com/example/notekeeper/NoteController.java
Labels: improvement

#26 Ck/websockets
  frontend/package.json
  frontend/scripts/deployDistToJavaPackage.sh
  frontend/src/App.vue
  frontend/src/components/NoteElement.vue
  frontend/src/components/dialogs/ConfirmDialog.vue
  frontend/src/lang/de.ts
  frontend/src/lang/en.ts
  frontend/src/main.ts
  frontend/src/plugins/vuetify.ts
  frontend/yarn.lock
  pom.xml
  src/main/java/com/example/notekeeper/NoteController.java
  src/main/java/com/example/notekeeper/NotekeeperApplication.java
  src/main/resources/application.properties
  src/main/resources/public/css/app.03d60d39.css
  src/main/resources/public/favicon.ico
  src/main/resources/public/index.html
  src/main/resources/public/js/app.16920dbe.js
  src/main/resources/public/js/app.16920dbe.js.map
  src/main/resources/public/js/chunk-vendors.1cc9d326.js
  src/main/resources/public/js/chunk-vendors.1cc9d326.js.map
  target/classes/application.properties
  target/classes/com/example/notekeeper/Note.class
  target/classes/com/example/notekeeper/NoteController.class
  target/classes/com/example/notekeeper/NoteService.class
  target/classes/com/example/notekeeper/NotekeeperApplication.class
  target/classes/com/example/notekeeper/requests/PostRequestBody.class
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: java, vue

#28 Ck/design
  frontend/.gitignore
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/NoteElement.vue
  frontend/src/components/dialogs/ConfirmDialog.vue
  frontend/src/components/dialogs/LoginDialog.vue
  frontend/src/lang/de.ts
  frontend/src/lang/en.ts
  frontend/src/lang/index.ts
  frontend/src/main.ts
  frontend/src/middleware/NotesManager.ts
  frontend/src/middleware/UserManager.ts
  frontend/src/store/index.ts
  frontend/src/store/mainStore.ts
  frontend/src/types.ts
  frontend/yarn.lock
  src/main/java/com/example/notekeeper/NoteController.java
  src/main/java/com/example/notekeeper/NoteService.java
  src/main/resources/public/css/app.784f686c.css
  src/main/resources/public/css/chunk-vendors.a39c1925.css
  src/main/resources/public/favicon.ico
  src/main/resources/public/fonts/materialdesignicons-webfont.0766edc9.eot
  src/main/resources/public/fonts/materialdesignicons-webfont.714a4eee.ttf
  src/main/resources/public/fonts/materialdesignicons-webfont.e659bf56.woff
  src/main/resources/public/fonts/materialdesignicons-webfont.fbaef2a9.woff2
  src/main/resources/public/index.html
  src/main/resources/public/js/app.8ceab672.js
  src/main/resources/public/js/app.8ceab672.js.map
  src/main/resources/public/js/chunk-vendors.29014562.js
  src/main/resources/public/js/chunk-vendors.29014562.js.map
  target/classes/com/example/notekeeper/Note.class
  target/classes/com/example/notekeeper/NoteController.class
  target/classes/com/example/notekeeper/NoteService.class
  target/classes/com/example/notekeeper/NotekeeperApplication.class
  target/classes/com/example/notekeeper/requests/PostRequestBody.class
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: java, vue

#32 Rework: Readme
  README.md
  res-readme/Frontend.png
Labels: documentation, improvement
